/*
* Name : draw_macros.h
* Copyright : Hisoft
* Autor : ruanqingyong
* Date : 2012.01.06
* Description : 
*/

#ifndef __DRAW_MACROS_H__
#define __DRAW_MACROS_H__

/* resource */
//#define DRAW_SWITCH_TO_SMALL	DRAW_SWITCH_TO
#define DRAW_SWITCH_TO			"switch_to.png"//"switch_to_small.png"
#define DRAW_LIVE				"live.png"
#define DRAW_LIVE_VS			"vs_live.png"
#define DRAW_TAB_BUTTON_DOWN	"TabButton_P.png"
#define DRAW_TAB_BUTTON_UP		"TabButton_N.png"
#define DRAW_TEAM_RANKINGS		"team_rankings.png"
#define DRAW_TEAM_DETAIL		"team_deatil.png"
#define DRAW_LIST_TITILE		"list_title.png"
#define DRAW_SCORE_DETAIL_BG	"score_detail_bg.png"
#define DRAW_LIST_BG_DOWN	"panelbg_n.png"
#define DRAW_LIST_BG_UP		"panelbg_p.png"
//#define DRAW_TEAMS_UP		"teams_up.png"
#define DRAW_TEAMS_DOWN		"teams_down.png"
//#define DRAW_NEWS_PHOTOS_UP		"news_photos_up.png"
#define DRAW_NEWS_PHOTOS_DOWN		"news_photos_down.png"

#define DRAW_COM_CNT_IMG		"com_cnt.png"
#define DRAW_COM_LEFT_IMG		"com_left.png"
#define DRAW_COM_RIGHT_IMG		"com_right.png"

/* end resource */

#define DRAW_DEFAULT_CON_WIDTH		window->s_screen_width


#define DRAW_COLOR_69					0x696969
#define DRAW_COLOR_46					0x464646
#define DRAW_COLOR_93					0x939393
#define DRAW_COLOR_C4					0xc4c4c4

#define DRAW_COMMENTARY_CNT_COLOR_ONE	0xF9F9F9
#define DRAW_COMMENTARY_CNT_COLOR_TWO	0xECECEC
#define DRAW_COMMENTARY_FONT_COLOR_ONE	0x666666
#define DRAW_COMMENTARY_FONT_COLOR_TWO	0x8E8E8E
#define DRAW_NO_DATA_COLOR			0xE8E8E8
#define DRAW_RECENT_2ND_COLOR		0x676767//0x585858
#define DRAW_FLAG_ROUND_L_WIDTH		48
#define DRAW_FLAG_ROUND_L_HEIGHT	48
#define DRAW_FLAG_ROUND_S_WIDTH		32
#define DRAW_FLAG_ROUND_S_HEIGHT	32
#define DRAW_FLAG_LARGE_WIDTH		80//66
#define DRAW_FLAG_LARGE_HEIGHT		53//32
#define DRAW_FLAG_LARGE_BANK_WIDTH	65
#define DRAW_FLAG_LARGE_BANK_HEIGHT	37
#define DRAW_FLAG_SMALL_WIDTH		27
#define DRAW_FLAG_SMALL_HEIGHT		19
#define DRAW_PLAYER_HEAD_WIDTH		64
#define DRAW_PLAYER_HEAD_HEIGHT		64
#define DRAW_VS_WIDTH	60//87//51//34
#define DRAW_VS_HEIGHT	51//70//34//53
#define DRAW_MATCH_LIVE_WIDTH	47//34
#define DRAW_MATCH_LIVE_HEIGHT	24//11
#define DRAW_LIST_MEMBER_SWITCH_WIDTH	11//8
#define DRAW_LIST_MEMBER_SWITCH_HEIGHT	14//26
#define DRAW_GAC_BUF_LEN60	60
#define DRAW_GAC_BUF_LEN120	120
#define DRAW_GAC_BUF_LEN180	180
#define DRAW_GAC_BUF_LEN240	240
#define DRAW_GAC_BUF_LEN300	300
#define DRAW_GAC_BUF_LEN360	360
#define DRAW_GAC_BUF_LEN420	420
#define DRAW_GAC_BUF_LEN480	480
#define DRAW_GAC_BUF_LEN540	540


#ifdef __HVGA_H__
#define DRAW_SCORE_DETAIL_HEAD_CNT_HEIGHT	59
#define DRAW_SHOW_NO_DATA_FONT_SIZE	16
#define DRAW_RECENT_FONT_SIZE_ONE	20//12
#define DRAW_RECENT_FONT_SIZE_TWO	15//9
#define DRAW_RECENT_FONT_SIZE_THREE	18//10
#define DRAW_TEAM_DETAIL_WIDTH		294
#define DRAW_TEAM_DETAIL_HEIGHT		124
#define DRAW_TEAM_RANGING_X_GAP		18//124
#define DRAW_SWITCH_TO_X				290
#define DRAW_SWITCH_TO_Y				29
/* news photos */
#define DRAW_NEWS_PHOTOS_WIDTH				308
#define DRAW_NEWS_PHOTOS_HEIGHT				85
#define DRAW_NEWS_PHOTOS_CNT_PADDING_TOP		5

#define DRAW_LIST_RECENT_TOP_PADDING		4
#define DRAW_LIST_LIMIT_LEN_RECENT			19//22//32//22//25//17
#define DRAW_LIST_LIMIT_LEN_RECENT_ONE		26//32//22//17
#define DRAW_LIST_LIMIT_LEN_RECENT_TWO		19//22//26
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP_ONE	12//20//18
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP		9//18//10//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_DOWN	20//22//25//20
#define DRAW_LIST_LIMIT_LEN_ONGOING_ONE		12//20//16//21//13
#define DRAW_LIST_LIMIT_LEN_ONGOING_TWO		12//6//5
#define DRAW_LIST_LIMIT_LEN_ONGOING_THREE	22//35
#define DRAW_LIST_LIMIT_LEN_FIXTURES		32//20
#define DRAW_SCORE_DETAIL_NAME_X_GAP	6
#define DRAW_BATMAN_WIDTH		40//32
#define DRAW_BATMAN_HEIGHT		40//32
#define DRAW_MATCH_DETAIL_MATCH_LABEL_Y_GAP	5
#define DRAW_PLAYER_MAX_WIDTH_GAP			18//6
#define DRAW_TEAM_DETAIL_MAX_WIDTH_GAP		3
#define DRAW_TEAM_MAX_WIDTH_GAP				6
#define DRAW_LIVE_FLAG_WIDTH	DRAW_FLAG_ROUND_L_WIDTH
#define DRAW_LIVE_FLAG_HEIGHT	DRAW_FLAG_ROUND_L_HEIGHT
#define DRAW_MATCH_LIST_FLAG_WIDTH	DRAW_FLAG_ROUND_S_WIDTH
#define DRAW_MATCH_LIST_FLAG_HEIGHT	DRAW_FLAG_ROUND_S_HEIGHT
#define DRAW_MATCH_LIST_FLAG_IMG	team_flag_img
#define DRAW_MATCH_ONGOING_Y_GAP	0
/* draw_set_list_member */
#define DRAW_LIST_MEMBER_CNT_X_GAP		13//20
#define DRAW_LIST_MEMBER_CNT_WIDTH		294//(window->s_screen_width - (DRAW_LIST_MEMBER_CNT_X_GAP << 1))//2*20//- 2*DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_LIST_MEMBER_CNT_HEIGHT		35//50
#define DRAW_LIST_MEMBER_FONT_SIZE		19//20//18
#define DRAW_LIST_MEMBER_BR_ROUND		5
#define DRAW_LIST_MEMBER_SWITCH_X		(DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 5)// - 5 - 8//DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH -5
#define DRAW_LIST_MEMBER_SWITCH_Y		((DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//12//(50 - 26) >> 1//(DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1
#define DRAW_LIST_MEMBER_DEF_COLOR		0x4E4E4E//COLOR_WHITE//0xbfbfbf//COLOR_TOP_GRAY
#define DRAW_LIST_MEMBER_HOVER_COLOR	COLOR_MSG_ORANGE//0x404040
#define DRAW_LIST_MEMBER_LEFT_X			17
/* end draw_set_list_member */

/* draw_show_viewmore */
#define DRAW_VIEWMORE_HEIGHT	26
/* end draw_show_viewmore */



/* match */
#define	DRAW_MATCH_NO_DATA_Y	90
#define	DRAW_MATCH_LIST_CON_GAP	6
#define	DRAW_MATCH_CON_ROUND	6
#define DRAW_MATCH_LIST_CON_WIDTH	308//(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))
#define DRAW_MATCH_LIST_CON_HEIGHT	85//118
#define DRAW_MATCH_CON_BR_COLOR	COLOR_WHITE//0x0
#define DRAW_MATCH_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_MATCH_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_MATCH_CAL_Y_GAP	8
#define DRAW_MATCH_LINE_Y_GAP	1
#define DRAW_MATCH_VS_Y_GAP		3
#define DRAW_MATCH_VS_FLAG_GAP	5
#define DRAW_MATCH_P_T_PADDING	4
#define DRAW_MATCH_PLACE_Y_GAP	3
#define DRAW_MATCH_TEAMS_Y_GAP	1
#define DRAW_MATCH_LIST_Y_GAP	3
#define DRAW_MATCH_LIST_Y2_GAP	(3 + DRAW_LIST_MEMBER_CNT_HEIGHT)//53//3 + DRAW_LIST_MEMBER_CNT_HEIGHT
#define	DRAW_MATCH_LINE_WIDTH	DRAW_DEFAULT_CON_WIDTH//window->s_screen_width
#define	DRAW_MATCH_LINE_HEIGHT	1
#define DRAW_MATCH_RECENT_FLAG_X_GAP	12
#define DRAW_MATCH_RECENT_FLAG_X_GAP_TP	0//22//DRAW_MATCH_RECENT_FLAG_X_GAP + 6
#define DRAW_MATCH_UPCOMING_FLAG_X		0
#define DRAW_MATCH_RECENT_FLAG_Y_GAP	2//1
#define DRAW_MATCH_RECENT_FLAG1_Y_GAP	12
#define DRAW_MATCH_RECENT_FLAG2_Y_GAP	19
#define DRAW_MATCH_LIST_TEXT_FONT		FONT_MEDIUM
#define DRAW_MATCH_RECENT_TEXT_X		(DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_ROUND_S_WIDTH + 6)//45//12+6+27//DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_RECENT_PLACE_Y_GAP	-8//1//4//1//15
#define DRAW_MATCH_RECENT_GOAL_ONE_Y_GAP	-5//0//2//3
#define DRAW_MATCH_RECENT_GOAL_Y_GAP	10//16//1//15
#define DRAW_MATCH_SWITCH_X		(DRAW_MATCH_LIST_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 6)//-6-11//12 is switch width, 6 is gap
#define DRAW_MATCH_SWITCH_Y		(((DRAW_MATCH_LIST_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1) - 7)//36//(118-14)>> 1//(DRAW_MATCH_LIST_CON_HEIGHT - 14) >> 1//14 is switch height
#define DRAW_MATCH_LIVE_X		26//229//(DRAW_MATCH_LIST_CON_WIDTH - DRAW_MATCH_LIVE_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 12)//-18-34-6//18 = 12 + 6, 12 is switch width, 6 is gap
#define DRAW_MATCH_LIVE_Y		50//40//50//DRAW_MATCH_SWITCH_Y - 5//(DRAW_MATCH_SWITCH_Y + 36)//62//DRAW_MATCH_SWITCH_Y + 36
#define DRAW_MATCH_UPCOMING_PLACE_X_GAP	1//5
#define DRAW_MATCH_NOT_RECENT_GOAL_Y_GAP	2
#define DRAW_MATCH_POINT_OFFSET		11
#define DRAW_MATCH_LIST_NO_DATA_Y	30
/* end match */

/* player */
#define DRAW_PLAYER_SCORE_CNT_HEIGHT	48//32
#define DRAW_PLAYER_HEAD_Y_GAP		5
#define	DRAW_PLAYER_SWITCH_IMG_X_GAP	(DRAW_PLAYER_INNING_X_GAP + 8)//13//5+8
//#define	DRAW_PLAYER_SWITCH_IMG_HEIGHT	26//((DRAW_PLAYER_CON_HEIGHT - 26) >> 1)//12//(50-26)>>1
#define	DRAW_PLAYER_INNING_X_GAP	8
#define DRAW_PLAYER_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_PLAYER_CON_DEF_COLOR	COLOR_WHITE//0x98ff
#define	DRAW_PLAYER_HEAD_X			10
#define	DRAW_PLAYER_NAME_X_GAP		8
/* end player */

/* team */
#define	DRAW_TEAM_CON_WIDTH		DRAW_MATCH_LIST_CON_WIDTH//window->s_screen_width
#define	DRAW_TEAM_CON_HEIGHT		50
#define	DRAW_TEAM_CON_BR_COLOR	COLOR_WHITE//DRAW_MATCH_CON_BR_COLOR/*0x6666*/
#define DRAW_TEAM_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_TEAM_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_TEAM_HEAD_TEAM_X		10//4
#define DRAW_TEAM_X_GAP				23
/* end team */

/* commentary */
//#define DRAW_CMT_CON_WIDTH	(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//2*6//6 is right gap
#define DRAW_CMT_CON_PADDING_BOTTOM	6
#define DRAW_CMT_HEAD_TXT_WIDTH		(DRAW_DEFAULT_CON_WIDTH) >> 1
#define DRAW_CMT_HEAD_TXT_HEIGHT	28
#define DRAW_CMT_DEF_COLOR			COLOR_WHITE
#define DRAW_CMT_HOVER_COLOR		0x9800
#define DRAW_CMT_SCORE_X			18
#define DRAW_CMT_SCORE_Y			12
#define DRAW_CMT_NUM_X				26
#define DRAW_CMT_NUM_Y_GAP			6
#define DRAW_CMT_TXT_X				58
#define DRAW_CMT_TXT_D_Y_GAP		(DRAW_CMT_SCORE_Y + 2)//14//2+12//DRAW_CMT_SCORE_Y
#define DRAW_CMT_TXT_PADDING_LEFT	2
/* end commentary */

/* team player detail */
#define DRAW_T_P_CNT_HEAD_HEIGHT		28
#define DRAW_T_P_HEAD_M_X	188
#define DRAW_T_P_HEAD_A_X	268
#define DRAW_T_P_TXT_Y		8
#define DRAW_T_P_TXT_X		6
#define DRAW_T_P_CNT_HEIGHT		38
#define DRAW_T_P_CNT_WIDTH		(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//DRAW_DEFAULT_CON_WIDTH - 2*6//6 is right gap
#define DRAW_T_P_COACH_X		5//198
/* end team player detail */

/* match_detail */
#define DRAW_MATCH_DETAIL_FLAG_WIDTH	48//DRAW_FLAG_LARGE_WIDTH//DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_DETAIL_FLAG_HEIGHT	48//DRAW_FLAG_LARGE_HEIGHT//DRAW_FLAG_LARGE_HEIGHT
//#define DRAW_MATCH_DETAIL_VS_WIDTH		DRAW_VS_WIDTH
//#define DRAW_MATCH_DETAIL_VS_HEIGHT		DRAW_VS_HEIGHT
#define DRAW_MATCH_DETAIL_FLAG_BIND		team_flag_big_img//team_flag_small_img
#define DRAW_MATCH_DETAIL_CAL_Y		8
#define DRAW_MATCH_DETAIL_VS_Y_GAP	5
#define DRAW_MATCH_DETAIL_FLAG_GAP			5
#define DRAW_MATCH_DETAIL_PROGRESS_Y_GAP	2
#define DRAW_MATCH_DETAIL_TEAMS_Y_GAP	3
#define DRAW_MATCH_DETAIL_PLACE_Y_GAP	6
#define DRAW_MATCH_DETAIL_GOAL_Y_GAP	5
#define DRAW_MATCH_DETAIL_MATCH_Y_GAP	10
#define DRAW_MATCH_UPCOM_CNT_PADDING_BOTTOM	147//150//165//178//108
#define DRAW_MATCH_RECENT_CNT_PADDING_BOTTOM	38//41//50//2
#define DRAW_MATCH_ONGOING_CNT_PADDING_BOTTOM	52//46//76//87//96//26
#define DRAW_MATCH_DETAIL_L_FLAG_X		48
#define DRAW_MATCH_DETAIL_R_TXT_X		255//268
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y_GAP	9//28
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y1_GAP	10//8//5
/* end match_detail */

/* team_detail */
#define DRAW_TEAM_DETAIL_FLAG_X			52//((DRAW_DEFAULT_CON_WIDTH - DRAW_FLAG_LARGE_BANK_WIDTH/*DRAW_FLAG_LARGE_WIDTH*/) >> 1)
#define DRAW_TEAM_DETAIL_FLAG_Y			35//70//26//8
#define DRAW_TEAM_DETAIL_TEAM_NAME_X		20//10//31//6
#define DRAW_TEAM_DETAIL_IMG_X		DRAW_LIST_MEMBER_CNT_X_GAP//20//DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT		40//64
#define DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH		DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT
#define DRAW_TEAM_DETAIL_HEAD_IMG_Y_GAP		6
#define DRAW_TEAM_DETAIL_NAME_X		12//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH + 11)//95//20+64+11//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_IMG_WIDTH)
#define DRAW_TEAM_DETAIL_NAME_Y_GAP	6
#define DRAW_TEAM_DETAIL_CNT_PADDING_BOTTOM		9//42//50//55//15
#define DRAW_TEAM_DETAIL_RANKINGS_WIDTH		DRAW_LIST_MEMBER_CNT_WIDTH
#define DRAW_TEAM_DETAIL_RANKINGS_HEIGHT	36//39//28
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_WIDTH	(DRAW_TEAM_DETAIL_RANKINGS_WIDTH / 3)
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_X		(DRAW_TEAM_DETAIL_RANKINGS_WIDTH >> 1)
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_Y	25//9
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_X_GAP	22//38//8
#define DRAW_TEAM_DETAIL_ODI_TEXT_X_GAP			60
#define DRAW_TEAM_DETAIL_TEST_TEXT_X_GAP		8
#define DRAW_TEAM_DETAIL_TEXT_RECT_WIDTH		146//96
/* end team_detail */

/* fixtures */
#define DRAW_FIXTURES_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_FIXTURES_CON_HEIGHT	DRAW_MATCH_LIST_CON_HEIGHT//85
#define DRAW_FIXTURES_CON_DEF_COLOR	DRAW_MATCH_CON_DEF_COLOR
#define DRAW_FIXTURES_CON_HOVER_COLOR DRAW_MATCH_CON_HOVER_COLOR
#define DRAW_FIXTURES_SWITCH_X	(DRAW_FIXTURES_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 7)//-7-11//11 is switch width
#define DRAW_FIXTURES_SWITCH_Y	((DRAW_FIXTURES_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//35//(85-14)>>1//14 is switch is height
#define DRAW_FIXTURES_FLAG_X_GAP	12
#define DRAW_FIXTURES_FLAG1_Y_GAP	12
#define DRAW_FIXTURES_FLAG2_Y_GAP	4//19
#define DRAW_FIXTURES_Y_ONE_GAP		-3
#define DRAW_FIXTURES_TEXT_X	48
#define DRAW_FIXTURES_TEXT_Y	9
#define DRAW_FIXTURES_TEXT_Y_GAP	-1//6
#define DRAW_FIXTURES_DATE_OFFSET	11
#define DRAW_FIXTURES_TYPE_X		285//292 - 7
#define DRAW_FIXTURES_TYPE_Y		5
/* end fixtures */

/* draw head two head list message */
#define DRAW_HTH_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_HTH_CON_HEIGHT	38
#define DRAW_HTH_TEXT_Y		3//9
#define DRAW_HTH_IND_X		18
#define DRAW_HTH_WI_X		9//(DRAW_HTH_CON_WIDTH - 28)
#define DRAW_HTH_HEAD_HEIGHT	22//28
#define DRAW_HTH_STR_ARR_NUM	12
#define DRAW_HTH_STR_LEN1	7
#define DRAW_HTH_STR_LEN2	14
/* end head two head list message */

/* score detail */
#define DRAW_SCORE_DETAIL_BG_Y			11
#define DRAW_SCORE_DETAIL_TEXT_Y_GAP		6
#define DRAW_SCORE_DETAIL_TEXT_X			5
#define DRAW_SCORE_DETAIL_INNINGS_X_GAP		6
#define DRAW_SCORE_DETAIL_LINE_HEIGHT		1
#define DRAW_SCORE_DETAIL_HEAD_LINE_Y_GAP	12//2
#define DRAW_SCORE_DETAIL_BATTING_Y_GAP		4
#define DRAW_SCORE_DETAIL_BAT_TEXT_X		140//142//150//126
#define DRAW_SCORE_DETAIL_BOW_TEXT_X		86//50
#define DRAW_SCORE_DETAIL_TEXT_X_GAP	32//38
#define DRAW_SCORE_DETAIL_TEXT_MID_Y		22
#define DRAW_SCORE_DETAIL_HEAD_PADDING_B	3
/* end score detail */

#endif

#ifdef __QVGA_H__
#define DRAW_SCORE_DETAIL_HEAD_CNT_HEIGHT	59
#define DRAW_SHOW_NO_DATA_FONT_SIZE	16
#define DRAW_RECENT_FONT_SIZE_ONE	20//12
#define DRAW_RECENT_FONT_SIZE_TWO	15//9
#define DRAW_RECENT_FONT_SIZE_THREE	18//10
#define DRAW_TEAM_DETAIL_WIDTH		224//294
#define DRAW_TEAM_DETAIL_HEIGHT		124
#define DRAW_TEAM_RANGING_X_GAP		12//124
#define DRAW_SWITCH_TO_X				210
#define DRAW_SWITCH_TO_Y				35
#define DRAW_MATCH_RECENT_FLAG_Y_GAP	5//1
#define DRAW_MATCH_RECENT_FLAG_X_GAP_TP	0//22//DRAW_MATCH_RECENT_FLAG_X_GAP + 6
#define DRAW_MATCH_UPCOMING_FLAG_X		0
#define DRAW_NEWS_PHOTOS_WIDTH				228
#define DRAW_NEWS_PHOTOS_HEIGHT				85
#define DRAW_LIST_LIMIT_LEN_RECENT_ONE		17//14//16//20//18//17//17
#define DRAW_LIST_LIMIT_LEN_RECENT_TWO		18//12//14
#define DRAW_NEWS_PHOTOS_CNT_PADDING_TOP		8

#define DRAW_LIST_RECENT_TOP_PADDING		8
#define DRAW_LIST_LIMIT_LEN_RECENT			17//11//22//15//23//17
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP_ONE		16//8//10//15//10//15//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP		18//5//6//12//6//8//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_DOWN	18//13//16//15//20//19//20
#define DRAW_LIST_LIMIT_LEN_ONGOING_ONE		13//15//10//15//11//18//13
#define DRAW_LIST_LIMIT_LEN_ONGOING_TWO		19//17//6//12//6//5
#define DRAW_LIST_LIMIT_LEN_ONGOING_THREE	18//15//25
#define DRAW_LIST_LIMIT_LEN_FIXTURES		23//20
#define DRAW_SCORE_DETAIL_NAME_X_GAP	3
#define DRAW_BATMAN_WIDTH		40//32
#define DRAW_BATMAN_HEIGHT		40//32
#define DRAW_MATCH_DETAIL_MATCH_LABEL_Y_GAP	5
#define DRAW_PLAYER_MAX_WIDTH_GAP			20//6
#define DRAW_TEAM_DETAIL_MAX_WIDTH_GAP		3
#define DRAW_TEAM_MAX_WIDTH_GAP				6
#define DRAW_LIVE_FLAG_WIDTH	DRAW_FLAG_ROUND_L_WIDTH
#define DRAW_LIVE_FLAG_HEIGHT	DRAW_FLAG_ROUND_L_HEIGHT
#define DRAW_MATCH_LIST_FLAG_WIDTH	DRAW_FLAG_ROUND_S_WIDTH
#define DRAW_MATCH_LIST_FLAG_HEIGHT	DRAW_FLAG_ROUND_S_HEIGHT
#define DRAW_MATCH_LIST_FLAG_IMG	team_flag_img
#define DRAW_MATCH_ONGOING_Y_GAP	3
/* draw_set_list_member */
#define DRAW_LIST_MEMBER_CNT_X_GAP		8//13//20
#define DRAW_LIST_MEMBER_CNT_WIDTH		224//(window->s_screen_width - (DRAW_LIST_MEMBER_CNT_X_GAP << 1))//2*20//- 2*DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_LIST_MEMBER_CNT_HEIGHT		30//35//50
#define DRAW_LIST_MEMBER_FONT_SIZE		19//20//18
#define DRAW_LIST_MEMBER_BR_ROUND		5
#define DRAW_LIST_MEMBER_SWITCH_X		(DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 5)// - 5 - 8//DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH -5
#define DRAW_LIST_MEMBER_SWITCH_Y		((DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//12//(50 - 26) >> 1//(DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1
#define DRAW_LIST_MEMBER_DEF_COLOR		0x4E4E4E//COLOR_WHITE//0xbfbfbf//COLOR_TOP_GRAY
#define DRAW_LIST_MEMBER_HOVER_COLOR	COLOR_MSG_ORANGE//0x404040
#define DRAW_LIST_MEMBER_LEFT_X			17
/* end draw_set_list_member */

/* draw_show_viewmore */
#define DRAW_VIEWMORE_HEIGHT	26
/* end draw_show_viewmore */



/* match */
#define	DRAW_MATCH_NO_DATA_Y	58//90
#define	DRAW_MATCH_LIST_CON_GAP	6
#define	DRAW_MATCH_CON_ROUND	6
#define DRAW_MATCH_LIST_CON_WIDTH	228//(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))
#define DRAW_MATCH_LIST_CON_HEIGHT	85//118
#define DRAW_MATCH_CON_BR_COLOR	COLOR_WHITE//0x0
#define DRAW_MATCH_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_MATCH_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_MATCH_CAL_Y_GAP	8
#define DRAW_MATCH_LINE_Y_GAP	1
#define DRAW_MATCH_VS_Y_GAP		3
#define DRAW_MATCH_VS_FLAG_GAP	5
#define DRAW_MATCH_P_T_PADDING	4
#define DRAW_MATCH_PLACE_Y_GAP	3
#define DRAW_MATCH_TEAMS_Y_GAP	1
#define DRAW_MATCH_LIST_Y_GAP	3
#define DRAW_MATCH_LIST_Y2_GAP	(3 + DRAW_LIST_MEMBER_CNT_HEIGHT)//53//3 + DRAW_LIST_MEMBER_CNT_HEIGHT
#define	DRAW_MATCH_LINE_WIDTH	DRAW_DEFAULT_CON_WIDTH//window->s_screen_width
#define	DRAW_MATCH_LINE_HEIGHT	1
#define DRAW_MATCH_RECENT_FLAG_X_GAP	4//8//12
#define DRAW_MATCH_RECENT_FLAG1_Y_GAP	10//12
#define DRAW_MATCH_RECENT_FLAG2_Y_GAP	19
#define DRAW_MATCH_LIST_TEXT_FONT		FONT_SMALL//FONT_MEDIUM
#define DRAW_MATCH_RECENT_TEXT_X		(DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_ROUND_S_WIDTH + 9)//45//12+6+27//DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_RECENT_PLACE_Y_GAP	-11//1//15
#define DRAW_MATCH_RECENT_GOAL_ONE_Y_GAP	-8//1//6
#define DRAW_MATCH_RECENT_GOAL_Y_GAP	5//9//19//3//18//15
#define DRAW_MATCH_SWITCH_X		(DRAW_MATCH_LIST_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 6)//-6-11//12 is switch width, 6 is gap
#define DRAW_MATCH_SWITCH_Y		(((DRAW_MATCH_LIST_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1) - 7)//36//(118-14)>> 1//(DRAW_MATCH_LIST_CON_HEIGHT - 14) >> 1//14 is switch height
#define DRAW_MATCH_LIVE_X		168//25//164//(DRAW_MATCH_LIST_CON_WIDTH - DRAW_MATCH_LIVE_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 12)//-18-34-6//18 = 12 + 6, 12 is switch width, 6 is gap
#define DRAW_MATCH_LIVE_Y		5//50//34//DRAW_MATCH_SWITCH_Y - 22//(DRAW_MATCH_SWITCH_Y + 36)//62//DRAW_MATCH_SWITCH_Y + 36
#define DRAW_MATCH_UPCOMING_PLACE_X_GAP	1//5
#define DRAW_MATCH_NOT_RECENT_GOAL_Y_GAP	6//2
#define DRAW_MATCH_POINT_OFFSET		11
#define DRAW_MATCH_LIST_NO_DATA_Y	30
/* end match */

/* player */
#define DRAW_PLAYER_SCORE_CNT_HEIGHT	48//32
#define DRAW_PLAYER_HEAD_Y_GAP		5
#define	DRAW_PLAYER_SWITCH_IMG_X_GAP	(DRAW_PLAYER_INNING_X_GAP + 8)//13//5+8
#define	DRAW_PLAYER_INNING_X_GAP	4//8
#define DRAW_PLAYER_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_PLAYER_CON_DEF_COLOR	COLOR_WHITE//0x98ff
#define	DRAW_PLAYER_HEAD_X			10
#define	DRAW_PLAYER_NAME_X_GAP		0//8
/* end player */

/* team */
#define	DRAW_TEAM_CON_WIDTH		DRAW_MATCH_LIST_CON_WIDTH//window->s_screen_width
#define	DRAW_TEAM_CON_HEIGHT		50
#define	DRAW_TEAM_CON_BR_COLOR	COLOR_WHITE//DRAW_MATCH_CON_BR_COLOR/*0x6666*/
#define DRAW_TEAM_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_TEAM_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_TEAM_HEAD_TEAM_X		10//4
#define DRAW_TEAM_X_GAP				23
/* end team */

/* commentary */
//#define DRAW_CMT_CON_WIDTH	(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//2*6//6 is right gap
#define DRAW_CMT_CON_PADDING_BOTTOM	6
#define DRAW_CMT_HEAD_TXT_WIDTH		(DRAW_DEFAULT_CON_WIDTH) >> 1
#define DRAW_CMT_HEAD_TXT_HEIGHT	28
#define DRAW_CMT_DEF_COLOR			COLOR_WHITE
#define DRAW_CMT_HOVER_COLOR		0x9800
#define DRAW_CMT_SCORE_X			18
#define DRAW_CMT_SCORE_Y			12
#define DRAW_CMT_NUM_X				26
#define DRAW_CMT_NUM_Y_GAP			6
#define DRAW_CMT_TXT_X				58
#define DRAW_CMT_TXT_D_Y_GAP		(DRAW_CMT_SCORE_Y + 2)//14//2+12//DRAW_CMT_SCORE_Y
#define DRAW_CMT_TXT_PADDING_LEFT	2
/* end commentary */

/* team player detail */
#define DRAW_T_P_CNT_HEAD_HEIGHT		28
#define DRAW_T_P_HEAD_M_X	188
#define DRAW_T_P_HEAD_A_X	268
#define DRAW_T_P_TXT_Y		8
#define DRAW_T_P_TXT_X		6
#define DRAW_T_P_CNT_HEIGHT		38
#define DRAW_T_P_CNT_WIDTH		(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//DRAW_DEFAULT_CON_WIDTH - 2*6//6 is right gap
#define DRAW_T_P_COACH_X		5//198
/* end team player detail */

/* match_detail */
#define DRAW_MATCH_DETAIL_FLAG_WIDTH	48//DRAW_FLAG_LARGE_WIDTH//DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_DETAIL_FLAG_HEIGHT	48//DRAW_FLAG_LARGE_HEIGHT//DRAW_FLAG_LARGE_HEIGHT
//#define DRAW_MATCH_DETAIL_VS_WIDTH		DRAW_VS_WIDTH
//#define DRAW_MATCH_DETAIL_VS_HEIGHT		DRAW_VS_HEIGHT
#define DRAW_MATCH_DETAIL_FLAG_BIND		team_flag_big_img//team_flag_small_img
#define DRAW_MATCH_DETAIL_CAL_Y		8
#define DRAW_MATCH_DETAIL_VS_Y_GAP	5
#define DRAW_MATCH_DETAIL_FLAG_GAP			5
#define DRAW_MATCH_DETAIL_PROGRESS_Y_GAP	2
#define DRAW_MATCH_DETAIL_TEAMS_Y_GAP	3
#define DRAW_MATCH_DETAIL_PLACE_Y_GAP	6
#define DRAW_MATCH_DETAIL_GOAL_Y_GAP	5
#define DRAW_MATCH_DETAIL_MATCH_Y_GAP	10
#define DRAW_MATCH_UPCOM_CNT_PADDING_BOTTOM	8//147//150//165//178//108
#define DRAW_MATCH_RECENT_CNT_PADDING_BOTTOM	8//38//41//50//2
#define DRAW_MATCH_ONGOING_CNT_PADDING_BOTTOM	8//76//87//96//26
#define DRAW_MATCH_DETAIL_L_FLAG_X		26//48
#define DRAW_MATCH_DETAIL_R_TXT_X		218//226//268
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y_GAP	8//28
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y1_GAP	1
/* end match_detail */

/* team_detail */
#define DRAW_TEAM_DETAIL_FLAG_X			39//((DRAW_DEFAULT_CON_WIDTH - DRAW_FLAG_LARGE_WIDTH) >> 1)
#define DRAW_TEAM_DETAIL_FLAG_Y			22//50//18//4//8
#define DRAW_TEAM_DETAIL_TEAM_NAME_X		16//24//2//6
#define DRAW_TEAM_DETAIL_IMG_X		DRAW_LIST_MEMBER_CNT_X_GAP//20//DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT		40//64
#define DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH		DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT
#define DRAW_TEAM_DETAIL_HEAD_IMG_Y_GAP		6
#define DRAW_TEAM_DETAIL_NAME_X		10//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH + 11)//95//20+64+11//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_IMG_WIDTH)
#define DRAW_TEAM_DETAIL_NAME_Y_GAP	5//6
#define DRAW_TEAM_DETAIL_CNT_PADDING_BOTTOM		8//55//15
#define DRAW_TEAM_DETAIL_RANKINGS_WIDTH		DRAW_LIST_MEMBER_CNT_WIDTH
#define DRAW_TEAM_DETAIL_RANKINGS_HEIGHT	27//37//28
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_WIDTH	(DRAW_TEAM_DETAIL_RANKINGS_WIDTH / 3)
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_X		(DRAW_TEAM_DETAIL_RANKINGS_WIDTH >> 1)
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_Y	17//9
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_X_GAP	22//5
#define DRAW_TEAM_DETAIL_ODI_TEXT_X_GAP			62//78//103
#define DRAW_TEAM_DETAIL_TEST_TEXT_X_GAP		4//155//202
#define DRAW_TEAM_DETAIL_TEXT_RECT_WIDTH		112//75
/* end team_detail */

/* fixtures */
#define DRAW_FIXTURES_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_FIXTURES_CON_HEIGHT	DRAW_MATCH_LIST_CON_HEIGHT//85
#define DRAW_FIXTURES_CON_DEF_COLOR	DRAW_MATCH_CON_DEF_COLOR
#define DRAW_FIXTURES_CON_HOVER_COLOR DRAW_MATCH_CON_HOVER_COLOR
#define DRAW_FIXTURES_SWITCH_X	(DRAW_FIXTURES_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 7)//-7-11//11 is switch width
#define DRAW_FIXTURES_SWITCH_Y	((DRAW_FIXTURES_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//35//(85-14)>>1//14 is switch is height
#define DRAW_FIXTURES_FLAG_X_GAP	3//12
#define DRAW_FIXTURES_FLAG1_Y_GAP	12
#define DRAW_FIXTURES_FLAG2_Y_GAP	4//9//19
#define DRAW_FIXTURES_Y_ONE_GAP		-3
#define DRAW_FIXTURES_TEXT_X	35//48
#define DRAW_FIXTURES_TEXT_Y	9
#define DRAW_FIXTURES_TEXT_Y_GAP	-1//6
#define DRAW_FIXTURES_DATE_OFFSET	11
#define DRAW_FIXTURES_TYPE_X		208//218 - 10
#define DRAW_FIXTURES_TYPE_Y		5
/* end fixtures */

/* draw head two head list message */
#define DRAW_HTH_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_HTH_CON_HEIGHT	38
#define DRAW_HTH_TEXT_Y		6//9
#define DRAW_HTH_IND_X		18
#define DRAW_HTH_WI_X		9//(DRAW_HTH_CON_WIDTH - 28)
#define DRAW_HTH_HEAD_HEIGHT	22//28
#define DRAW_HTH_STR_ARR_NUM	12
#define DRAW_HTH_STR_LEN1	7
#define DRAW_HTH_STR_LEN2	14
/* end head two head list message */

/* score detail */
#define DRAW_SCORE_DETAIL_BG_Y			11
#define DRAW_SCORE_DETAIL_TEXT_Y_GAP		6
#define DRAW_SCORE_DETAIL_TEXT_X			2//5
#define DRAW_SCORE_DETAIL_INNINGS_X_GAP		6
#define DRAW_SCORE_DETAIL_LINE_HEIGHT		1
#define DRAW_SCORE_DETAIL_HEAD_LINE_Y_GAP	12//2
#define DRAW_SCORE_DETAIL_BATTING_Y_GAP		4
#define DRAW_SCORE_DETAIL_BAT_TEXT_X		90//92//106//150//126
#define DRAW_SCORE_DETAIL_BOW_TEXT_X		50//54//86//50
#define DRAW_SCORE_DETAIL_TEXT_X_GAP	25//26//32//38
#define DRAW_SCORE_DETAIL_TEXT_MID_Y		22
#define DRAW_SCORE_DETAIL_HEAD_PADDING_B	3
/* end score detail */


#endif

#ifdef __WQVGA_H__
#define DRAW_SCORE_DETAIL_HEAD_CNT_HEIGHT	59
#define DRAW_SHOW_NO_DATA_FONT_SIZE	16
#define DRAW_RECENT_FONT_SIZE_ONE	20//12
#define DRAW_RECENT_FONT_SIZE_TWO	15//9
#define DRAW_RECENT_FONT_SIZE_THREE	18//10
#define DRAW_TEAM_DETAIL_WIDTH		224
#define DRAW_TEAM_DETAIL_HEIGHT		124
#define DRAW_TEAM_RANGING_X_GAP		12//124
#define DRAW_SWITCH_TO_X				210
#define DRAW_SWITCH_TO_Y				35
#define DRAW_MATCH_RECENT_FLAG_Y_GAP	5//1
#define DRAW_MATCH_RECENT_FLAG_X_GAP_TP	0//22//DRAW_MATCH_RECENT_FLAG_X_GAP + 6
#define DRAW_MATCH_UPCOMING_FLAG_X		0
#define DRAW_NEWS_PHOTOS_WIDTH				228
#define DRAW_NEWS_PHOTOS_HEIGHT				85
#define DRAW_LIST_LIMIT_LEN_RECENT_ONE		17//14//20//17//17
#define DRAW_LIST_LIMIT_LEN_RECENT_TWO		18//12//14
#define DRAW_NEWS_PHOTOS_CNT_PADDING_TOP		8

#define DRAW_LIST_RECENT_TOP_PADDING		8
#define DRAW_LIST_LIMIT_LEN_RECENT			17//11//22//15//23//17
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP_ONE		16//8//10//15//9//15//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP		18//5//6//12//6//8//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_DOWN	18//13//16//19//20
#define DRAW_LIST_LIMIT_LEN_ONGOING_ONE		13//10//15//10//18//13
#define DRAW_LIST_LIMIT_LEN_ONGOING_TWO		19//6//12//-5//6//5
#define DRAW_LIST_LIMIT_LEN_ONGOING_THREE	18//15//25
#define DRAW_LIST_LIMIT_LEN_FIXTURES		23//20
#define DRAW_SCORE_DETAIL_NAME_X_GAP	3
#define DRAW_BATMAN_WIDTH		40//32
#define DRAW_BATMAN_HEIGHT		40//32
#define DRAW_MATCH_DETAIL_MATCH_LABEL_Y_GAP	5
#define DRAW_PLAYER_MAX_WIDTH_GAP			20//6
#define DRAW_TEAM_DETAIL_MAX_WIDTH_GAP		3
#define DRAW_TEAM_MAX_WIDTH_GAP				6
#define DRAW_LIVE_FLAG_WIDTH	DRAW_FLAG_ROUND_L_WIDTH
#define DRAW_LIVE_FLAG_HEIGHT	DRAW_FLAG_ROUND_L_HEIGHT
#define DRAW_MATCH_LIST_FLAG_WIDTH	DRAW_FLAG_ROUND_S_WIDTH
#define DRAW_MATCH_LIST_FLAG_HEIGHT	DRAW_FLAG_ROUND_S_HEIGHT
#define DRAW_MATCH_LIST_FLAG_IMG	team_flag_img
#define DRAW_MATCH_ONGOING_Y_GAP	3

/* draw_set_list_member */
#define DRAW_LIST_MEMBER_CNT_X_GAP		8//20
#define DRAW_LIST_MEMBER_CNT_WIDTH		224//(window->s_screen_width - (DRAW_LIST_MEMBER_CNT_X_GAP << 1))//2*20//- 2*DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_LIST_MEMBER_CNT_HEIGHT		30//35//50
#define DRAW_LIST_MEMBER_FONT_SIZE		19//20//18
#define DRAW_LIST_MEMBER_BR_ROUND		5
#define DRAW_LIST_MEMBER_SWITCH_X		(DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 5)// - 5 - 8//DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH -5
#define DRAW_LIST_MEMBER_SWITCH_Y		((DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//12//(50 - 26) >> 1//(DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1
#define DRAW_LIST_MEMBER_DEF_COLOR		0x4E4E4E//COLOR_WHITE//0xbfbfbf//COLOR_TOP_GRAY
#define DRAW_LIST_MEMBER_HOVER_COLOR	COLOR_MSG_ORANGE//0x404040
#define DRAW_LIST_MEMBER_LEFT_X			17
/* end draw_set_list_member */

/* draw_show_viewmore */
#define DRAW_VIEWMORE_HEIGHT	26
/* end draw_show_viewmore */



/* match */
#define	DRAW_MATCH_NO_DATA_Y	105//58//90
#define	DRAW_MATCH_LIST_CON_GAP	6
#define	DRAW_MATCH_CON_ROUND	6
#define DRAW_MATCH_LIST_CON_WIDTH	228//(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))
#define DRAW_MATCH_LIST_CON_HEIGHT	85//118
#define DRAW_MATCH_CON_BR_COLOR	COLOR_WHITE//0x0
#define DRAW_MATCH_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_MATCH_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_MATCH_CAL_Y_GAP	8
#define DRAW_MATCH_LINE_Y_GAP	1
#define DRAW_MATCH_VS_Y_GAP		3
#define DRAW_MATCH_VS_FLAG_GAP	5
#define DRAW_MATCH_P_T_PADDING	4
#define DRAW_MATCH_PLACE_Y_GAP	3
#define DRAW_MATCH_TEAMS_Y_GAP	1
#define DRAW_MATCH_LIST_Y_GAP	3
#define DRAW_MATCH_LIST_Y2_GAP	(3 + DRAW_LIST_MEMBER_CNT_HEIGHT)//53//3 + DRAW_LIST_MEMBER_CNT_HEIGHT
#define	DRAW_MATCH_LINE_WIDTH	DRAW_DEFAULT_CON_WIDTH//window->s_screen_width
#define	DRAW_MATCH_LINE_HEIGHT	1
#define DRAW_MATCH_RECENT_FLAG_X_GAP	4//8//12
#define DRAW_MATCH_RECENT_FLAG1_Y_GAP	10//12
#define DRAW_MATCH_RECENT_FLAG2_Y_GAP	19
#define DRAW_MATCH_LIST_TEXT_FONT		FONT_SMALL//FONT_MEDIUM
#define DRAW_MATCH_RECENT_TEXT_X		(DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_ROUND_S_WIDTH + 9)//45//12+6+27//DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_RECENT_PLACE_Y_GAP	-11//-9//1//15
#define DRAW_MATCH_RECENT_GOAL_Y_GAP	5//19//3//18//15
#define DRAW_MATCH_RECENT_GOAL_ONE_Y_GAP	-8//1//6
#define DRAW_MATCH_SWITCH_X		(DRAW_MATCH_LIST_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 6)//-6-11//12 is switch width, 6 is gap
#define DRAW_MATCH_SWITCH_Y		(((DRAW_MATCH_LIST_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1) - 7)//36//(118-14)>> 1//(DRAW_MATCH_LIST_CON_HEIGHT - 14) >> 1//14 is switch height
#define DRAW_MATCH_LIVE_X		168//25//164//(DRAW_MATCH_LIST_CON_WIDTH - DRAW_MATCH_LIVE_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 12)//-18-34-6//18 = 12 + 6, 12 is switch width, 6 is gap
#define DRAW_MATCH_LIVE_Y		5//50//34//DRAW_MATCH_SWITCH_Y - 5//(DRAW_MATCH_SWITCH_Y + 36)//62//DRAW_MATCH_SWITCH_Y + 36
#define DRAW_MATCH_UPCOMING_PLACE_X_GAP	1//5
#define DRAW_MATCH_NOT_RECENT_GOAL_Y_GAP	6//2
#define DRAW_MATCH_POINT_OFFSET		11
#define DRAW_MATCH_LIST_NO_DATA_Y	30
/* end match */

/* player */
#define DRAW_PLAYER_SCORE_CNT_HEIGHT	48//32
#define DRAW_PLAYER_HEAD_Y_GAP		5
#define	DRAW_PLAYER_SWITCH_IMG_X_GAP	(DRAW_PLAYER_INNING_X_GAP + 5)//13//5+8
#define	DRAW_PLAYER_INNING_X_GAP	4//8
#define DRAW_PLAYER_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_PLAYER_CON_DEF_COLOR	COLOR_WHITE//0x98ff
#define	DRAW_PLAYER_HEAD_X			10
#define	DRAW_PLAYER_NAME_X_GAP		0//8
/* end player */

/* team */
#define	DRAW_TEAM_CON_WIDTH		DRAW_MATCH_LIST_CON_WIDTH//window->s_screen_width
#define	DRAW_TEAM_CON_HEIGHT		50
#define	DRAW_TEAM_CON_BR_COLOR	COLOR_WHITE//DRAW_MATCH_CON_BR_COLOR/*0x6666*/
#define DRAW_TEAM_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_TEAM_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_TEAM_HEAD_TEAM_X		10//4
#define DRAW_TEAM_X_GAP				23
/* end team */

/* commentary */
//#define DRAW_CMT_CON_WIDTH	(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//2*6//6 is right gap
#define DRAW_CMT_CON_PADDING_BOTTOM	6
#define DRAW_CMT_HEAD_TXT_WIDTH		(DRAW_DEFAULT_CON_WIDTH) >> 1
#define DRAW_CMT_HEAD_TXT_HEIGHT	28
#define DRAW_CMT_DEF_COLOR			COLOR_WHITE
#define DRAW_CMT_HOVER_COLOR		0x9800
#define DRAW_CMT_SCORE_X			18
#define DRAW_CMT_SCORE_Y			12
#define DRAW_CMT_NUM_X				26
#define DRAW_CMT_NUM_Y_GAP			6
#define DRAW_CMT_TXT_X				58
#define DRAW_CMT_TXT_D_Y_GAP		(DRAW_CMT_SCORE_Y + 2)//14//2+12//DRAW_CMT_SCORE_Y
#define DRAW_CMT_TXT_PADDING_LEFT	2
/* end commentary */

/* team player detail */
#define DRAW_T_P_CNT_HEAD_HEIGHT		28
#define DRAW_T_P_HEAD_M_X	188
#define DRAW_T_P_HEAD_A_X	268
#define DRAW_T_P_TXT_Y		8
#define DRAW_T_P_TXT_X		6
#define DRAW_T_P_CNT_HEIGHT		38
#define DRAW_T_P_CNT_WIDTH		(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//DRAW_DEFAULT_CON_WIDTH - 2*6//6 is right gap
#define DRAW_T_P_COACH_X		5//198
/* end team player detail */

/* match_detail */
#define DRAW_MATCH_DETAIL_FLAG_WIDTH	48//DRAW_FLAG_LARGE_WIDTH//DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_DETAIL_FLAG_HEIGHT	48//DRAW_FLAG_LARGE_HEIGHT//DRAW_FLAG_LARGE_HEIGHT
//#define DRAW_MATCH_DETAIL_VS_WIDTH		DRAW_VS_WIDTH
//#define DRAW_MATCH_DETAIL_VS_HEIGHT		DRAW_VS_HEIGHT
#define DRAW_MATCH_DETAIL_FLAG_BIND		team_flag_big_img//team_flag_small_img
#define DRAW_MATCH_DETAIL_CAL_Y		8
#define DRAW_MATCH_DETAIL_VS_Y_GAP	5
#define DRAW_MATCH_DETAIL_FLAG_GAP			5
#define DRAW_MATCH_DETAIL_PROGRESS_Y_GAP	2
#define DRAW_MATCH_DETAIL_TEAMS_Y_GAP	3
#define DRAW_MATCH_DETAIL_PLACE_Y_GAP	6
#define DRAW_MATCH_DETAIL_GOAL_Y_GAP	5
#define DRAW_MATCH_DETAIL_MATCH_Y_GAP	10
#define DRAW_MATCH_UPCOM_CNT_PADDING_BOTTOM	96//9//147//150//165//178//108
#define DRAW_MATCH_RECENT_CNT_PADDING_BOTTOM	8//38//41//50//2
#define DRAW_MATCH_ONGOING_CNT_PADDING_BOTTOM	8//9//76//87//96//26
#define DRAW_MATCH_DETAIL_L_FLAG_X		26//48
#define DRAW_MATCH_DETAIL_R_TXT_X		218//226//268
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y_GAP	8//28
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y1_GAP	1
/* end match_detail */

/* team_detail */
#define DRAW_TEAM_DETAIL_FLAG_X			39//((DRAW_DEFAULT_CON_WIDTH - DRAW_FLAG_LARGE_WIDTH) >> 1)
#define DRAW_TEAM_DETAIL_FLAG_Y			36//22//50//18//4//8
#define DRAW_TEAM_DETAIL_TEAM_NAME_X		16//24//2//6
#define DRAW_TEAM_DETAIL_IMG_X		DRAW_LIST_MEMBER_CNT_X_GAP//20//DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT		40//64
#define DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH		DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT
#define DRAW_TEAM_DETAIL_HEAD_IMG_Y_GAP		6
#define DRAW_TEAM_DETAIL_NAME_X		10//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH + 11)//95//20+64+11//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_IMG_WIDTH)
#define DRAW_TEAM_DETAIL_NAME_Y_GAP	5//6
#define DRAW_TEAM_DETAIL_CNT_PADDING_BOTTOM		28//6//8//55//15
#define DRAW_TEAM_DETAIL_RANKINGS_WIDTH		DRAW_LIST_MEMBER_CNT_WIDTH
#define DRAW_TEAM_DETAIL_RANKINGS_HEIGHT	27//37//28
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_WIDTH	(DRAW_TEAM_DETAIL_RANKINGS_WIDTH / 3)
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_X		(DRAW_TEAM_DETAIL_RANKINGS_WIDTH >> 1)
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_Y	17//9
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_X_GAP	22//5
#define DRAW_TEAM_DETAIL_ODI_TEXT_X_GAP		62//	78//103
#define DRAW_TEAM_DETAIL_TEST_TEXT_X_GAP	4//	155//202
#define DRAW_TEAM_DETAIL_TEXT_RECT_WIDTH		112//75
/* end team_detail */

/* fixtures */
#define DRAW_FIXTURES_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_FIXTURES_CON_HEIGHT	DRAW_MATCH_LIST_CON_HEIGHT//85
#define DRAW_FIXTURES_CON_DEF_COLOR	DRAW_MATCH_CON_DEF_COLOR
#define DRAW_FIXTURES_CON_HOVER_COLOR DRAW_MATCH_CON_HOVER_COLOR
#define DRAW_FIXTURES_SWITCH_X	(DRAW_FIXTURES_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 7)//-7-11//11 is switch width
#define DRAW_FIXTURES_SWITCH_Y	((DRAW_FIXTURES_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//35//(85-14)>>1//14 is switch is height
#define DRAW_FIXTURES_FLAG_X_GAP	3//12
#define DRAW_FIXTURES_FLAG1_Y_GAP	12
#define DRAW_FIXTURES_FLAG2_Y_GAP	4//9//19
#define DRAW_FIXTURES_Y_ONE_GAP		-3
#define DRAW_FIXTURES_TEXT_X	35//48
#define DRAW_FIXTURES_TEXT_Y	9
#define DRAW_FIXTURES_TEXT_Y_GAP	-1//6
#define DRAW_FIXTURES_DATE_OFFSET	11
#define DRAW_FIXTURES_TYPE_X		208//218 - 10
#define DRAW_FIXTURES_TYPE_Y		5
/* end fixtures */

/* draw head two head list message */
#define DRAW_HTH_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_HTH_CON_HEIGHT	38
#define DRAW_HTH_TEXT_Y		6//9
#define DRAW_HTH_IND_X		18
#define DRAW_HTH_WI_X		9//(DRAW_HTH_CON_WIDTH - 28)
#define DRAW_HTH_HEAD_HEIGHT	22//28
#define DRAW_HTH_STR_ARR_NUM	12
#define DRAW_HTH_STR_LEN1	7
#define DRAW_HTH_STR_LEN2	14
/* end head two head list message */

/* score detail */
#define DRAW_SCORE_DETAIL_BG_Y			11
#define DRAW_SCORE_DETAIL_TEXT_Y_GAP		6
#define DRAW_SCORE_DETAIL_TEXT_X			2//5
#define DRAW_SCORE_DETAIL_INNINGS_X_GAP		6
#define DRAW_SCORE_DETAIL_LINE_HEIGHT		1
#define DRAW_SCORE_DETAIL_HEAD_LINE_Y_GAP	12//2
#define DRAW_SCORE_DETAIL_BATTING_Y_GAP		4
#define DRAW_SCORE_DETAIL_BAT_TEXT_X		90//92//106//150//126
#define DRAW_SCORE_DETAIL_BOW_TEXT_X		50//54//86//50
#define DRAW_SCORE_DETAIL_TEXT_X_GAP	25//26//32//38
#define DRAW_SCORE_DETAIL_TEXT_MID_Y		22
#define DRAW_SCORE_DETAIL_HEAD_PADDING_B	3
/* end score detail */

#endif

#ifdef __QCIF_H__
#define DRAW_SCORE_DETAIL_HEAD_CNT_HEIGHT	59
#define DRAW_SHOW_NO_DATA_FONT_SIZE	16
#define DRAW_RECENT_FONT_SIZE_ONE	12//20//12
#define DRAW_RECENT_FONT_SIZE_TWO	9//15//9
#define DRAW_RECENT_FONT_SIZE_THREE	10//18//10
#define DRAW_TEAM_DETAIL_WIDTH		160//294
#define DRAW_TEAM_DETAIL_HEIGHT		124//124
#define DRAW_TEAM_RANGING_X_GAP		8//124
#define DRAW_SWITCH_TO_X				150
#define DRAW_SWITCH_TO_Y				35
#define DRAW_MATCH_RECENT_FLAG_Y_GAP	4//1
#define DRAW_MATCH_RECENT_FLAG_X_GAP_TP	0//28//0//28//22//DRAW_MATCH_RECENT_FLAG_X_GAP + 6
#define DRAW_MATCH_UPCOMING_FLAG_X		11//10
#define DRAW_NEWS_PHOTOS_WIDTH				308
#define DRAW_NEWS_PHOTOS_HEIGHT				85
#define DRAW_NEWS_PHOTOS_CNT_PADDING_TOP		8

#define DRAW_LIST_RECENT_TOP_PADDING		9
#define DRAW_LIST_LIMIT_LEN_RECENT			14//9//11//10//11//17
#define DRAW_LIST_LIMIT_LEN_RECENT_ONE		13//15//9//8//12//17//17
#define DRAW_LIST_LIMIT_LEN_RECENT_TWO		16//18//19
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP_ONE	14//9//6//8//6//15
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP		13//4//3//5//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_DOWN	16//20//10//16//21//20
#define DRAW_LIST_LIMIT_LEN_ONGOING_ONE		12//8//9//14//13
#define DRAW_LIST_LIMIT_LEN_ONGOING_TWO		16//4//3//5//5
#define DRAW_LIST_LIMIT_LEN_ONGOING_THREE	16//12//10
#define DRAW_LIST_LIMIT_LEN_FIXTURES		18//20
#define DRAW_SCORE_DETAIL_NAME_X_GAP	3
#define DRAW_BATMAN_WIDTH		40//32
#define DRAW_BATMAN_HEIGHT		40//32
#define DRAW_PLAYER_MAX_WIDTH_GAP			16///6
#define DRAW_TEAM_DETAIL_MAX_WIDTH_GAP		3
#define DRAW_TEAM_MAX_WIDTH_GAP				6
#define DRAW_MATCH_DETAIL_MATCH_LABEL_Y_GAP	7
#define DRAW_LIVE_FLAG_WIDTH	32//DRAW_FLAG_ROUND_L_WIDTH
#define DRAW_LIVE_FLAG_HEIGHT	32//DRAW_FLAG_ROUND_L_HEIGHT
#define DRAW_MATCH_LIST_FLAG_WIDTH	DRAW_FLAG_ROUND_S_WIDTH
#define DRAW_MATCH_LIST_FLAG_HEIGHT	DRAW_FLAG_ROUND_S_HEIGHT
#define DRAW_MATCH_LIST_FLAG_IMG	team_flag_img
#define DRAW_MATCH_ONGOING_Y_GAP	3
/* draw_set_list_member */
#define DRAW_LIST_MEMBER_CNT_X_GAP		8//13//20
#define DRAW_LIST_MEMBER_CNT_WIDTH		160//(window->s_screen_width - (DRAW_LIST_MEMBER_CNT_X_GAP << 1))//2*20//- 2*DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_LIST_MEMBER_CNT_HEIGHT		25//30//35//50
#define DRAW_LIST_MEMBER_FONT_SIZE		19//20//18
#define DRAW_LIST_MEMBER_BR_ROUND		5
#define DRAW_LIST_MEMBER_SWITCH_X		(DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 5)// - 5 - 8//DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH -5
#define DRAW_LIST_MEMBER_SWITCH_Y		((DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//12//(50 - 26) >> 1//(DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1
#define DRAW_LIST_MEMBER_DEF_COLOR		0x4E4E4E//COLOR_WHITE//0xbfbfbf//COLOR_TOP_GRAY
#define DRAW_LIST_MEMBER_HOVER_COLOR	COLOR_MSG_ORANGE//0x404040
#define DRAW_LIST_MEMBER_LEFT_X			17
/* end draw_set_list_member */

/* draw_show_viewmore */
#define DRAW_VIEWMORE_HEIGHT	26
/* end draw_show_viewmore */

/* match */
#define	DRAW_MATCH_NO_DATA_Y	30//58//90
#define	DRAW_MATCH_LIST_CON_GAP	6
#define	DRAW_MATCH_CON_ROUND	6
#define DRAW_MATCH_LIST_CON_WIDTH	164//(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))
#define DRAW_MATCH_LIST_CON_HEIGHT	85//105//118
#define DRAW_MATCH_CON_BR_COLOR	COLOR_WHITE//0x0
#define DRAW_MATCH_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_MATCH_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_MATCH_CAL_Y_GAP	8
#define DRAW_MATCH_LINE_Y_GAP	1
#define DRAW_MATCH_VS_Y_GAP		3
#define DRAW_MATCH_VS_FLAG_GAP	5
#define DRAW_MATCH_P_T_PADDING	4
#define DRAW_MATCH_PLACE_Y_GAP	3
#define DRAW_MATCH_TEAMS_Y_GAP	1
#define DRAW_MATCH_LIST_Y_GAP	3
#define DRAW_MATCH_LIST_Y2_GAP	(3 + DRAW_LIST_MEMBER_CNT_HEIGHT)//53//3 + DRAW_LIST_MEMBER_CNT_HEIGHT
#define	DRAW_MATCH_LINE_WIDTH	DRAW_DEFAULT_CON_WIDTH//window->s_screen_width
#define	DRAW_MATCH_LINE_HEIGHT	1
#define DRAW_MATCH_RECENT_FLAG_X_GAP	2//4//5//8//12
#define DRAW_MATCH_RECENT_FLAG1_Y_GAP	8//12
#define DRAW_MATCH_RECENT_FLAG2_Y_GAP	19
#define DRAW_MATCH_LIST_TEXT_FONT		FONT_SMALL//FONT_MEDIUM
#define DRAW_MATCH_RECENT_TEXT_X		(DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_ROUND_S_WIDTH + 5/*9*/)//45//12+6+27//DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_RECENT_PLACE_Y_GAP	-7//-10//2//6//21//15
#define DRAW_MATCH_RECENT_GOAL_ONE_Y_GAP	-9//-7//1//6
#define DRAW_MATCH_RECENT_GOAL_Y_GAP	10//8//16//0//3//18//15
#define DRAW_MATCH_SWITCH_X		(DRAW_MATCH_LIST_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 6)//-6-11//12 is switch width, 6 is gap
#define DRAW_MATCH_SWITCH_Y		(((DRAW_MATCH_LIST_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1) - 3)//7//36//(118-14)>> 1//(DRAW_MATCH_LIST_CON_HEIGHT - 14) >> 1//14 is switch height
#define DRAW_MATCH_LIVE_X		115//18//95//(DRAW_MATCH_LIST_CON_WIDTH - DRAW_MATCH_LIVE_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 12)//-18-34-6//18 = 12 + 6, 12 is switch width, 6 is gap
#define DRAW_MATCH_LIVE_Y		5//50//38//DRAW_MATCH_SWITCH_Y - 5//(DRAW_MATCH_SWITCH_Y + 36)//62//DRAW_MATCH_SWITCH_Y + 36
#define DRAW_MATCH_UPCOMING_PLACE_X_GAP	0//5
#define DRAW_MATCH_NOT_RECENT_GOAL_Y_GAP	6//2
#define DRAW_MATCH_POINT_OFFSET		11
#define DRAW_MATCH_LIST_NO_DATA_Y	30
/* end match */

/* player */
#define DRAW_PLAYER_SCORE_CNT_HEIGHT	64//48//32
#define DRAW_PLAYER_HEAD_Y_GAP		5
#define	DRAW_PLAYER_SWITCH_IMG_X_GAP	(DRAW_PLAYER_INNING_X_GAP + 8)//13//5+8
#define	DRAW_PLAYER_INNING_X_GAP	4//8
#define DRAW_PLAYER_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_PLAYER_CON_DEF_COLOR	COLOR_WHITE//0x98ff
#define	DRAW_PLAYER_HEAD_X			5//10
#define	DRAW_PLAYER_NAME_X_GAP		0//8
/* end player */

/* team */
#define	DRAW_TEAM_CON_WIDTH		DRAW_MATCH_LIST_CON_WIDTH//window->s_screen_width
#define	DRAW_TEAM_CON_HEIGHT		50
#define	DRAW_TEAM_CON_BR_COLOR	COLOR_WHITE//DRAW_MATCH_CON_BR_COLOR/*0x6666*/
#define DRAW_TEAM_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_TEAM_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_TEAM_HEAD_TEAM_X		6//10//4
#define DRAW_TEAM_X_GAP				12//23
/* end team */

/* commentary */
//#define DRAW_CMT_CON_WIDTH	(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//2*6//6 is right gap
#define DRAW_CMT_CON_PADDING_BOTTOM	6
#define DRAW_CMT_HEAD_TXT_WIDTH		(DRAW_DEFAULT_CON_WIDTH) >> 1
#define DRAW_CMT_HEAD_TXT_HEIGHT	28
#define DRAW_CMT_DEF_COLOR			COLOR_WHITE
#define DRAW_CMT_HOVER_COLOR		0x9800
#define DRAW_CMT_SCORE_X			18
#define DRAW_CMT_SCORE_Y			12
#define DRAW_CMT_NUM_X				26
#define DRAW_CMT_NUM_Y_GAP			6
#define DRAW_CMT_TXT_X				58
#define DRAW_CMT_TXT_D_Y_GAP		(DRAW_CMT_SCORE_Y + 2)//14//2+12//DRAW_CMT_SCORE_Y
#define DRAW_CMT_TXT_PADDING_LEFT	2
/* end commentary */

/* team player detail */
#define DRAW_T_P_CNT_HEAD_HEIGHT		28
#define DRAW_T_P_HEAD_M_X	188
#define DRAW_T_P_HEAD_A_X	268
#define DRAW_T_P_TXT_Y		8
#define DRAW_T_P_TXT_X		6
#define DRAW_T_P_CNT_HEIGHT		38
#define DRAW_T_P_CNT_WIDTH		(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//DRAW_DEFAULT_CON_WIDTH - 2*6//6 is right gap
#define DRAW_T_P_COACH_X		5//198
/* end team player detail */

/* match_detail */
#define DRAW_MATCH_DETAIL_FLAG_WIDTH	48//DRAW_FLAG_SMALL_WIDTH//DRAW_FLAG_LARGE_WIDTH
#define DRAW_MATCH_DETAIL_FLAG_HEIGHT	48//DRAW_FLAG_LARGE_HEIGHT//DRAW_FLAG_LARGE_HEIGHT
//#define DRAW_MATCH_DETAIL_VS_WIDTH		20//DRAW_VS_WIDTH
//#define DRAW_MATCH_DETAIL_VS_HEIGHT		17//DRAW_VS_HEIGHT
#define DRAW_MATCH_DETAIL_FLAG_BIND		/*team_flag_small_img*/team_flag_big_img
#define DRAW_MATCH_DETAIL_CAL_Y		8
#define DRAW_MATCH_DETAIL_VS_Y_GAP	5
#define DRAW_MATCH_DETAIL_FLAG_GAP	1//5//10//5
#define DRAW_MATCH_DETAIL_PROGRESS_Y_GAP	2
#define DRAW_MATCH_DETAIL_TEAMS_Y_GAP	3
#define DRAW_MATCH_DETAIL_PLACE_Y_GAP	6
#define DRAW_MATCH_DETAIL_GOAL_Y_GAP	5
#define DRAW_MATCH_DETAIL_MATCH_Y_GAP	10
#define DRAW_MATCH_UPCOM_CNT_PADDING_BOTTOM	8//147//150//165//178//108
#define DRAW_MATCH_RECENT_CNT_PADDING_BOTTOM	8//38//41//50//2
#define DRAW_MATCH_ONGOING_CNT_PADDING_BOTTOM	8//76//87//96//26
#define DRAW_MATCH_DETAIL_L_FLAG_X		9//26//48
#define DRAW_MATCH_DETAIL_R_TXT_X		155//163//226//268
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y_GAP	6//28
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y1_GAP	0
/* end match_detail */

/* team_detail */
#define DRAW_TEAM_DETAIL_FLAG_X			19//29//((DRAW_DEFAULT_CON_WIDTH - DRAW_FLAG_LARGE_WIDTH) >> 1)
#define DRAW_TEAM_DETAIL_FLAG_Y			12//4//8
#define DRAW_TEAM_DETAIL_TEAM_NAME_X		6//16//2//6
#define DRAW_TEAM_DETAIL_IMG_X		DRAW_LIST_MEMBER_CNT_X_GAP//20//DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT		40//64
#define DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH		DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT
#define DRAW_TEAM_DETAIL_HEAD_IMG_Y_GAP		6
#define DRAW_TEAM_DETAIL_NAME_X		10//6//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH + 11)//95//20+64+11//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_IMG_WIDTH)
#define DRAW_TEAM_DETAIL_NAME_Y_GAP	2//5//6
#define DRAW_TEAM_DETAIL_CNT_PADDING_BOTTOM		6//55//15
#define DRAW_TEAM_DETAIL_RANKINGS_WIDTH		DRAW_LIST_MEMBER_CNT_WIDTH
#define DRAW_TEAM_DETAIL_RANKINGS_HEIGHT	21//18//37//28
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_WIDTH	(DRAW_TEAM_DETAIL_RANKINGS_WIDTH / 3)
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_X		(DRAW_TEAM_DETAIL_RANKINGS_WIDTH >> 1)
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_Y	10//17//9//6
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_X_GAP	16//3//5
#define DRAW_TEAM_DETAIL_ODI_TEXT_X_GAP			63//58//103
#define DRAW_TEAM_DETAIL_TEST_TEXT_X_GAP		4//112//202
#define DRAW_TEAM_DETAIL_TEXT_RECT_WIDTH		80//76//72//53
/* end team_detail */

/* fixtures */
#define DRAW_FIXTURES_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_FIXTURES_CON_HEIGHT	DRAW_MATCH_LIST_CON_HEIGHT//85
#define DRAW_FIXTURES_CON_DEF_COLOR	DRAW_MATCH_CON_DEF_COLOR
#define DRAW_FIXTURES_CON_HOVER_COLOR DRAW_MATCH_CON_HOVER_COLOR
#define DRAW_FIXTURES_SWITCH_X	(DRAW_FIXTURES_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 7)//-7-11//11 is switch width
#define DRAW_FIXTURES_SWITCH_Y	((DRAW_FIXTURES_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//35//(85-14)>>1//14 is switch is height
#define DRAW_FIXTURES_FLAG_X_GAP	3//12
#define DRAW_FIXTURES_FLAG1_Y_GAP	12
#define DRAW_FIXTURES_FLAG2_Y_GAP	4//9//19
#define DRAW_FIXTURES_Y_ONE_GAP		-3
#define DRAW_FIXTURES_TEXT_X	35//48
#define DRAW_FIXTURES_TEXT_Y	9
#define DRAW_FIXTURES_TEXT_Y_GAP	-1//6
#define DRAW_FIXTURES_DATE_OFFSET	11
#define DRAW_FIXTURES_TYPE_X		142//150 - 8
#define DRAW_FIXTURES_TYPE_Y		5
/* end fixtures */

/* draw head two head list message */
#define DRAW_HTH_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_HTH_CON_HEIGHT	38
#define DRAW_HTH_TEXT_Y		6//9
#define DRAW_HTH_IND_X		18
#define DRAW_HTH_WI_X		9//(DRAW_HTH_CON_WIDTH - 28)
#define DRAW_HTH_HEAD_HEIGHT	22//28
#define DRAW_HTH_STR_ARR_NUM	12
#define DRAW_HTH_STR_LEN1	7
#define DRAW_HTH_STR_LEN2	14
/* end head two head list message */

/* score detail */
#define DRAW_SCORE_DETAIL_BG_Y			11
#define DRAW_SCORE_DETAIL_TEXT_Y_GAP		6
#define DRAW_SCORE_DETAIL_TEXT_X			2//5
#define DRAW_SCORE_DETAIL_INNINGS_X_GAP		6
#define DRAW_SCORE_DETAIL_LINE_HEIGHT		1
#define DRAW_SCORE_DETAIL_HEAD_LINE_Y_GAP	12//10//20//12//2
#define DRAW_SCORE_DETAIL_BATTING_Y_GAP		4
#define DRAW_SCORE_DETAIL_BAT_TEXT_X		57//61//64//66//92//106//150//126
#define DRAW_SCORE_DETAIL_BOW_TEXT_X		54//86//50
#define DRAW_SCORE_DETAIL_TEXT_X_GAP	20//19//20//26//32//38
#define DRAW_SCORE_DETAIL_TEXT_MID_Y		22
#define DRAW_SCORE_DETAIL_HEAD_PADDING_B	3
/* end score detail */

#endif

#ifdef __LQVGA_H__
#define DRAW_SCORE_DETAIL_HEAD_CNT_HEIGHT	59
#define DRAW_SHOW_NO_DATA_FONT_SIZE	16
#define DRAW_RECENT_FONT_SIZE_ONE	20//12
#define DRAW_RECENT_FONT_SIZE_TWO	15//9
#define DRAW_RECENT_FONT_SIZE_THREE	18//10
#define DRAW_TEAM_DETAIL_WIDTH		294
#define DRAW_TEAM_DETAIL_HEIGHT		124
#define DRAW_TEAM_RANGING_X_GAP		18//124
#define DRAW_SWITCH_TO_X				290
#define DRAW_SWITCH_TO_Y				29
/* news photos */
#define DRAW_NEWS_PHOTOS_WIDTH				308
#define DRAW_NEWS_PHOTOS_HEIGHT				85
#define DRAW_NEWS_PHOTOS_CNT_PADDING_TOP		5

#define DRAW_LIST_RECENT_TOP_PADDING		4
#define DRAW_LIST_LIMIT_LEN_RECENT			19//22//32//22//25//17
#define DRAW_LIST_LIMIT_LEN_RECENT_ONE		26//32//22//17
#define DRAW_LIST_LIMIT_LEN_RECENT_TWO		19//22//26
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP_ONE	12//20//18
#define DRAW_LIST_LIMIT_LEN_UPCOMING_UP		9//18//10//5
#define DRAW_LIST_LIMIT_LEN_UPCOMING_DOWN	20//22//25//20
#define DRAW_LIST_LIMIT_LEN_ONGOING_ONE		12//20//16//21//13
#define DRAW_LIST_LIMIT_LEN_ONGOING_TWO		12//6//5
#define DRAW_LIST_LIMIT_LEN_ONGOING_THREE	22//35
#define DRAW_LIST_LIMIT_LEN_FIXTURES		32//20
#define DRAW_SCORE_DETAIL_NAME_X_GAP	6
#define DRAW_BATMAN_WIDTH		40//32
#define DRAW_BATMAN_HEIGHT		40//32
#define DRAW_MATCH_DETAIL_MATCH_LABEL_Y_GAP	5
#define DRAW_PLAYER_MAX_WIDTH_GAP			18//6
#define DRAW_TEAM_DETAIL_MAX_WIDTH_GAP		3
#define DRAW_TEAM_MAX_WIDTH_GAP				6
#define DRAW_LIVE_FLAG_WIDTH	DRAW_FLAG_ROUND_L_WIDTH
#define DRAW_LIVE_FLAG_HEIGHT	DRAW_FLAG_ROUND_L_HEIGHT
#define DRAW_MATCH_LIST_FLAG_WIDTH	DRAW_FLAG_ROUND_S_WIDTH
#define DRAW_MATCH_LIST_FLAG_HEIGHT	DRAW_FLAG_ROUND_S_HEIGHT
#define DRAW_MATCH_LIST_FLAG_IMG	team_flag_img
#define DRAW_MATCH_ONGOING_Y_GAP	0
/* draw_set_list_member */
#define DRAW_LIST_MEMBER_CNT_X_GAP		13//20
#define DRAW_LIST_MEMBER_CNT_WIDTH		294//(window->s_screen_width - (DRAW_LIST_MEMBER_CNT_X_GAP << 1))//2*20//- 2*DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_LIST_MEMBER_CNT_HEIGHT		35//50
#define DRAW_LIST_MEMBER_FONT_SIZE		19//20//18
#define DRAW_LIST_MEMBER_BR_ROUND		5
#define DRAW_LIST_MEMBER_SWITCH_X		(DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 5)// - 5 - 8//DRAW_LIST_MEMBER_CNT_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH -5
#define DRAW_LIST_MEMBER_SWITCH_Y		((DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//12//(50 - 26) >> 1//(DRAW_LIST_MEMBER_CNT_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1
#define DRAW_LIST_MEMBER_DEF_COLOR		0x4E4E4E//COLOR_WHITE//0xbfbfbf//COLOR_TOP_GRAY
#define DRAW_LIST_MEMBER_HOVER_COLOR	COLOR_MSG_ORANGE//0x404040
#define DRAW_LIST_MEMBER_LEFT_X			8//17
/* end draw_set_list_member */

/* draw_show_viewmore */
#define DRAW_VIEWMORE_HEIGHT	26
/* end draw_show_viewmore */



/* match */
#define	DRAW_MATCH_NO_DATA_Y	40//90
#define	DRAW_MATCH_LIST_CON_GAP	6
#define	DRAW_MATCH_CON_ROUND	6
#define DRAW_MATCH_LIST_CON_WIDTH	308//(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))
#define DRAW_MATCH_LIST_CON_HEIGHT	85//118
#define DRAW_MATCH_CON_BR_COLOR	COLOR_WHITE//0x0
#define DRAW_MATCH_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_MATCH_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_MATCH_CAL_Y_GAP	8
#define DRAW_MATCH_LINE_Y_GAP	1
#define DRAW_MATCH_VS_Y_GAP		3
#define DRAW_MATCH_VS_FLAG_GAP	5
#define DRAW_MATCH_P_T_PADDING	4
#define DRAW_MATCH_PLACE_Y_GAP	3
#define DRAW_MATCH_TEAMS_Y_GAP	1
#define DRAW_MATCH_LIST_Y_GAP	3
#define DRAW_MATCH_LIST_Y2_GAP	(3 + DRAW_LIST_MEMBER_CNT_HEIGHT)//53//3 + DRAW_LIST_MEMBER_CNT_HEIGHT
#define	DRAW_MATCH_LINE_WIDTH	DRAW_DEFAULT_CON_WIDTH//window->s_screen_width
#define	DRAW_MATCH_LINE_HEIGHT	1
#define DRAW_MATCH_RECENT_FLAG_X_GAP	12
#define DRAW_MATCH_RECENT_FLAG_X_GAP_TP	0//22//DRAW_MATCH_RECENT_FLAG_X_GAP + 6
#define DRAW_MATCH_UPCOMING_FLAG_X		0
#define DRAW_MATCH_RECENT_FLAG_Y_GAP	2//1
#define DRAW_MATCH_RECENT_FLAG1_Y_GAP	12
#define DRAW_MATCH_RECENT_FLAG2_Y_GAP	19
#define DRAW_MATCH_LIST_TEXT_FONT		FONT_MEDIUM
#define DRAW_MATCH_RECENT_TEXT_X		(DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_ROUND_S_WIDTH + 6)//45//12+6+27//DRAW_MATCH_RECENT_FLAG_X_GAP + DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_RECENT_PLACE_Y_GAP	-8//1//4//1//15
#define DRAW_MATCH_RECENT_GOAL_ONE_Y_GAP	-5//0//2//3
#define DRAW_MATCH_RECENT_GOAL_Y_GAP	10//16//1//15
#define DRAW_MATCH_SWITCH_X		(DRAW_MATCH_LIST_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 6)//-6-11//12 is switch width, 6 is gap
#define DRAW_MATCH_SWITCH_Y		(((DRAW_MATCH_LIST_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1) - 7)//36//(118-14)>> 1//(DRAW_MATCH_LIST_CON_HEIGHT - 14) >> 1//14 is switch height
#define DRAW_MATCH_LIVE_X		26//229//(DRAW_MATCH_LIST_CON_WIDTH - DRAW_MATCH_LIVE_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 12)//-18-34-6//18 = 12 + 6, 12 is switch width, 6 is gap
#define DRAW_MATCH_LIVE_Y		50//40//50//DRAW_MATCH_SWITCH_Y - 5//(DRAW_MATCH_SWITCH_Y + 36)//62//DRAW_MATCH_SWITCH_Y + 36
#define DRAW_MATCH_UPCOMING_PLACE_X_GAP	1//5
#define DRAW_MATCH_NOT_RECENT_GOAL_Y_GAP	2
#define DRAW_MATCH_POINT_OFFSET		11
#define DRAW_MATCH_LIST_NO_DATA_Y	72//40 + TITLE_BAR_HEIGHT==32//30
/* end match */

/* player */
#define DRAW_PLAYER_SCORE_CNT_HEIGHT	48//32
#define DRAW_PLAYER_HEAD_Y_GAP		5
#define	DRAW_PLAYER_SWITCH_IMG_X_GAP	(DRAW_PLAYER_INNING_X_GAP + 8)//13//5+8
//#define	DRAW_PLAYER_SWITCH_IMG_HEIGHT	26//((DRAW_PLAYER_CON_HEIGHT - 26) >> 1)//12//(50-26)>>1
#define	DRAW_PLAYER_INNING_X_GAP	8
#define DRAW_PLAYER_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_PLAYER_CON_DEF_COLOR	COLOR_WHITE//0x98ff
#define	DRAW_PLAYER_HEAD_X			10
#define	DRAW_PLAYER_NAME_X_GAP		8
/* end player */

/* team */
#define	DRAW_TEAM_CON_WIDTH		DRAW_MATCH_LIST_CON_WIDTH//window->s_screen_width
#define	DRAW_TEAM_CON_HEIGHT		50
#define	DRAW_TEAM_CON_BR_COLOR	COLOR_WHITE//DRAW_MATCH_CON_BR_COLOR/*0x6666*/
#define DRAW_TEAM_CON_HOVER_COLOR	COLOR_MSG_ORANGE//0x3838
#define DRAW_TEAM_CON_DEF_COLOR	COLOR_WHITE
#define DRAW_TEAM_HEAD_TEAM_X		10//4
#define DRAW_TEAM_X_GAP				23
/* end team */

/* commentary */
//#define DRAW_CMT_CON_WIDTH	(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//2*6//6 is right gap
#define DRAW_CMT_CON_PADDING_BOTTOM	6
#define DRAW_CMT_HEAD_TXT_WIDTH		(DRAW_DEFAULT_CON_WIDTH) >> 1
#define DRAW_CMT_HEAD_TXT_HEIGHT	28
#define DRAW_CMT_DEF_COLOR			COLOR_WHITE
#define DRAW_CMT_HOVER_COLOR		0x9800
#define DRAW_CMT_SCORE_X			18
#define DRAW_CMT_SCORE_Y			12
#define DRAW_CMT_NUM_X				26
#define DRAW_CMT_NUM_Y_GAP			6
#define DRAW_CMT_TXT_X				58
#define DRAW_CMT_TXT_D_Y_GAP		(DRAW_CMT_SCORE_Y + 2)//14//2+12//DRAW_CMT_SCORE_Y
#define DRAW_CMT_TXT_PADDING_LEFT	2
/* end commentary */

/* team player detail */
#define DRAW_T_P_CNT_HEAD_HEIGHT		28
#define DRAW_T_P_HEAD_M_X	188
#define DRAW_T_P_HEAD_A_X	268
#define DRAW_T_P_TXT_Y		8
#define DRAW_T_P_TXT_X		6
#define DRAW_T_P_CNT_HEIGHT		38
#define DRAW_T_P_CNT_WIDTH		(window->s_screen_width - (DRAW_MATCH_LIST_CON_GAP << 1))//DRAW_DEFAULT_CON_WIDTH - 2*6//6 is right gap
#define DRAW_T_P_COACH_X		5//198
/* end team player detail */

/* match_detail */
#define DRAW_MATCH_DETAIL_FLAG_WIDTH	48//DRAW_FLAG_LARGE_WIDTH//DRAW_FLAG_SMALL_WIDTH
#define DRAW_MATCH_DETAIL_FLAG_HEIGHT	48//DRAW_FLAG_LARGE_HEIGHT//DRAW_FLAG_LARGE_HEIGHT
//#define DRAW_MATCH_DETAIL_VS_WIDTH		DRAW_VS_WIDTH
//#define DRAW_MATCH_DETAIL_VS_HEIGHT		DRAW_VS_HEIGHT
#define DRAW_MATCH_DETAIL_FLAG_BIND		team_flag_big_img//team_flag_small_img
#define DRAW_MATCH_DETAIL_CAL_Y		8
#define DRAW_MATCH_DETAIL_VS_Y_GAP	5
#define DRAW_MATCH_DETAIL_FLAG_GAP			5
#define DRAW_MATCH_DETAIL_PROGRESS_Y_GAP	2
#define DRAW_MATCH_DETAIL_TEAMS_Y_GAP	3
#define DRAW_MATCH_DETAIL_PLACE_Y_GAP	6
#define DRAW_MATCH_DETAIL_GOAL_Y_GAP	5
#define DRAW_MATCH_DETAIL_MATCH_Y_GAP	10
#define DRAW_MATCH_UPCOM_CNT_PADDING_BOTTOM	6//1//3//147//150//165//178//108
#define DRAW_MATCH_RECENT_CNT_PADDING_BOTTOM	6//1//3//38//41//50//2
#define DRAW_MATCH_ONGOING_CNT_PADDING_BOTTOM	6//1//3//52//46//76//87//96//26
#define DRAW_MATCH_DETAIL_L_FLAG_X		48
#define DRAW_MATCH_DETAIL_R_TXT_X		255//268
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y_GAP	9//28
#define DRAW_MATCH_DETAIL_FLAG_RECT_Y1_GAP	10//8//5
/* end match_detail */

/* team_detail */
#define DRAW_TEAM_DETAIL_FLAG_X			52//((DRAW_DEFAULT_CON_WIDTH - DRAW_FLAG_LARGE_BANK_WIDTH/*DRAW_FLAG_LARGE_WIDTH*/) >> 1)
#define DRAW_TEAM_DETAIL_FLAG_Y			35//70//26//8
#define DRAW_TEAM_DETAIL_TEAM_NAME_X		20//10//31//6
#define DRAW_TEAM_DETAIL_IMG_X		DRAW_LIST_MEMBER_CNT_X_GAP//20//DRAW_LIST_MEMBER_CNT_X_GAP
#define DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT		40//64
#define DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH		DRAW_TEAM_DETAIL_HEAD_IMG_HEIGHT
#define DRAW_TEAM_DETAIL_HEAD_IMG_Y_GAP		6
#define DRAW_TEAM_DETAIL_NAME_X		12//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_HEAD_IMG_WIDTH + 11)//95//20+64+11//(DRAW_TEAM_DETAIL_IMG_X + DRAW_TEAM_DETAIL_IMG_WIDTH)
#define DRAW_TEAM_DETAIL_NAME_Y_GAP	6
#define DRAW_TEAM_DETAIL_CNT_PADDING_BOTTOM		9//42//50//55//15
#define DRAW_TEAM_DETAIL_RANKINGS_WIDTH		DRAW_LIST_MEMBER_CNT_WIDTH
#define DRAW_TEAM_DETAIL_RANKINGS_HEIGHT	36//39//28
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_WIDTH	(DRAW_TEAM_DETAIL_RANKINGS_WIDTH / 3)
//#define DRAW_TEAM_DETAIL_RANKINGS_MID_X		(DRAW_TEAM_DETAIL_RANKINGS_WIDTH >> 1)
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_Y	25//9
#define DRAW_TEAM_DETAIL_RANKINGS_TEXT_X_GAP	22//38//8
#define DRAW_TEAM_DETAIL_ODI_TEXT_X_GAP			60
#define DRAW_TEAM_DETAIL_TEST_TEXT_X_GAP		8
#define DRAW_TEAM_DETAIL_TEXT_RECT_WIDTH		146//96
/* end team_detail */

/* fixtures */
#define DRAW_FIXTURES_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_FIXTURES_CON_HEIGHT	DRAW_MATCH_LIST_CON_HEIGHT//85
#define DRAW_FIXTURES_CON_DEF_COLOR	DRAW_MATCH_CON_DEF_COLOR
#define DRAW_FIXTURES_CON_HOVER_COLOR DRAW_MATCH_CON_HOVER_COLOR
#define DRAW_FIXTURES_SWITCH_X	(DRAW_FIXTURES_CON_WIDTH - DRAW_LIST_MEMBER_SWITCH_WIDTH - 7)//-7-11//11 is switch width
#define DRAW_FIXTURES_SWITCH_Y	((DRAW_FIXTURES_CON_HEIGHT - DRAW_LIST_MEMBER_SWITCH_HEIGHT) >> 1)//35//(85-14)>>1//14 is switch is height
#define DRAW_FIXTURES_FLAG_X_GAP	12
#define DRAW_FIXTURES_FLAG1_Y_GAP	12
#define DRAW_FIXTURES_FLAG2_Y_GAP	4//19
#define DRAW_FIXTURES_Y_ONE_GAP		-3
#define DRAW_FIXTURES_TEXT_X	48
#define DRAW_FIXTURES_TEXT_Y	9
#define DRAW_FIXTURES_TEXT_Y_GAP	-1//6
#define DRAW_FIXTURES_DATE_OFFSET	11
#define DRAW_FIXTURES_TYPE_X		285//292 - 7
#define DRAW_FIXTURES_TYPE_Y		5
/* end fixtures */

/* draw head two head list message */
#define DRAW_HTH_CON_WIDTH	DRAW_MATCH_LIST_CON_WIDTH
#define DRAW_HTH_CON_HEIGHT	38
#define DRAW_HTH_TEXT_Y		3//9
#define DRAW_HTH_IND_X		18
#define DRAW_HTH_WI_X		9//(DRAW_HTH_CON_WIDTH - 28)
#define DRAW_HTH_HEAD_HEIGHT	22//28
#define DRAW_HTH_STR_ARR_NUM	12
#define DRAW_HTH_STR_LEN1	7
#define DRAW_HTH_STR_LEN2	14
/* end head two head list message */

/* score detail */
#define DRAW_SCORE_DETAIL_BG_Y			11
#define DRAW_SCORE_DETAIL_TEXT_Y_GAP		6
#define DRAW_SCORE_DETAIL_TEXT_X			5
#define DRAW_SCORE_DETAIL_INNINGS_X_GAP		6
#define DRAW_SCORE_DETAIL_LINE_HEIGHT		1
#define DRAW_SCORE_DETAIL_HEAD_LINE_Y_GAP	12//2
#define DRAW_SCORE_DETAIL_BATTING_Y_GAP		4
#define DRAW_SCORE_DETAIL_BAT_TEXT_X		140//142//150//126
#define DRAW_SCORE_DETAIL_BOW_TEXT_X		86//50
#define DRAW_SCORE_DETAIL_TEXT_X_GAP	32//38
#define DRAW_SCORE_DETAIL_TEXT_MID_Y		22
#define DRAW_SCORE_DETAIL_HEAD_PADDING_B	3
/* end score detail */

#endif

#endif



/******************************* EOF ***********************************/
